name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Install the dotenv CLI tool to load the .env file
      - name: Install dotenv CLI
        run: sudo apt-get install -y dotenv

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      # Set up environment variables for PostgreSQL and from the .env file
      - name: Load environment variables from .env
        run: dotenv -f .env | tee -a $GITHUB_ENV

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Run linter
        run: cargo clippy -- -D warnings

      - name: Generate documentation
        run: cargo doc --no-deps --document-private-items
